### ISSUE TITLE
backup

### ISSUE THREAD

**Issue by Wjxfi** [NimaKhajehpour/MyMood#2]

**Comment by NimaKhajehpour** [comment]
Hey There @Wjxfi,  Thanks for using my app. I hope you enjted it! So can you provide some more info about what you want to be added in the app so that i can start working on it? :heart:

**Comment by NimaKhajehpour** [comment]
Thanks for providing more details on backup feature. Took a look at the example you sent and it is a good idea to add such feature for the app. Thanks for the suggestion, will work on implementing that in next update :heart:

**Comment by NimaKhajehpour** [comment]
Yeah i know but i am a student and have a limitted time to work on my apps so it might take time for me to actually get to work on it. Thanks for your patience ❤️

**Comment by NimaKhajehpour** [comment]
the update  is done now users can import and export their data as xml to/from the app. it is available under release tag of v1.1.0 and will be available in f-droid in next build cycle.

**Comment by NimaKhajehpour** [comment]
yes i did add the app to github release and it will be published to fdroid after a little bit. it is on release now
