### ISSUE TITLE
Permission Problems on Android 13

### ISSUE THREAD

**Issue by ahormann** [NimaKhajehpour/MyMood#20]
First of, i love the idea and style of your App. With the currently planned features I think it has a lot of potential!

But on both of my Android 13 devices the Export (and Import) does nothing (does not ask for permissions, does not give a popup, to my knowledge does not save an export (although i might not know where to look)).
In the settings of the App it says the App does not want any permissions.
I tried Versions 1.1.0 and 1.2.1.
On Android 12 it works.

**Comment by ahormann** [comment]
Unfortunately there are no files in my downloads folder. And the popup/toast that says the file is saved in the downloads folder does not appear on Android 13 either.

**Comment by NimaKhajehpour** [comment]
Ok so it is the storage management thing on android 13. I'll get on fixing it as soon as the app gets fixed for RB on fdroid again.

**Comment by NimaKhajehpour** [comment]
Ok so it is the storage management thing on android 13. I'll get on fixing it as soon as the app gets fixed for RB on fdroid again.

**Comment by NimaKhajehpour** [comment]
Ok so it is the storage management thing on android 13. I'll get on fixing it as soon as the app gets fixed for RB on fdroid again.
