### ISSUE TITLE
[Feature Request] Statistics with graphs

### ISSUE THREAD

**Issue by Terkyz** [NimaKhajehpour/MyMood#22]
It would be great to have the ability to have statistics with a graph summarizing the moods!

**Comment by NimaKhajehpour** [comment]
Ok I'll have to figure that out. Thanks for using the app and helping to improve it. Will figure it out and and it to the app. Thanks for your feature request and enjoy the app ❤️

**Comment by NimaKhajehpour** [comment]
Yes i have that planned for later releases on the app. I will make that and will add day compare with graph which you can add more than one day and have the graph show the details.

**Comment by NimaKhajehpour** [comment]
@Wjxfi so for the graph view for a certain range of dates, i decided to put a date range select so that user can decide how many days to select. so the short version is that the app wont have pre-defined ranges such as year and weeks and user should select them.
