### ISSUE TITLE
Should be affected, not effected

### ISSUE THREAD

**Issue by ZakOnGit** [NimaKhajehpour/MyMood#25]
https://github.com/NimaKhajehpour/MyMood/blob/ce62b10e9a6fcf82c041196497c16be7bcffc6cf/app/src/main/java/com/nima/mymood/screens/TodayMoodScreen.kt#LL470C50-L470C58

**Comment by NimaKhajehpour** [comment]
Thanks for letting me know! changes will apply in next update.

**Comment by ZakOnGit** [comment]
No problem! It also needs corrected in the promo art on Fdroid
