### ISSUE TITLE
insert the text of the message you want to change into the edit line

### ISSUE THREAD

**Issue by Wjxfi** [NimaKhajehpour/MyMood#26]
https://github.com/NimaKhajehpour/MyMood/assets/113500363/de8b1eb7-44c2-4230-bd99-e8c67a43daa8

**Comment by NimaKhajehpour** [comment]
Hey, so right now editting the effects is the way that if you have empty text on edit dialog it keeps the old description but i am going to change the editting system and the way it is handled in the future updates.
