### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [NimaKhajehpour/MyMood#33]
```
e: file:///builds/fdroid/fdroiddata/build/com.nima.mymood/app/src/main/java/com/nima/mymood/screens/DayScreen.kt:180:72 Unresolved reference: baseline_show_chart_24
e: file:///builds/fdroid/fdroiddata/build/com.nima.mymood/app/src/main/java/com/nima/mymood/screens/MenuScreen.kt:763:40 Unresolved reference: baseline_show_chart_24
```

Could you please take a look? Thanks!

**Comment by NimaKhajehpour** [comment]
hey there. so it failed again :(
are there any infos on why it failed?

**Comment by linsui** [comment]
I forgot to paste the log. Updated.

**Comment by NimaKhajehpour** [comment]
yeah so this is a weird one because project compiles well and uses that asset with no problem but it shows it in red for some reason

**Comment by NimaKhajehpour** [comment]
yeah got it
issue resolved.
will get new release and a maintenance tag.
it will be 1.5.1

**Comment by linsui** [comment]
Thanks!

**Comment by NimaKhajehpour** [comment]
new tag added. thanks for letting me know about the issue ❤️

**Comment by linsui** [comment]
It works, thanks!
