### ISSUE TITLE
feature request. around the date to show the face with the desired color

### ISSUE THREAD

**Issue by Wjxfi** [NimaKhajehpour/MyMood#5]
![340440.jpg](https://user-images.githubusercontent.com/113500363/224676935-9d6d7aa4-04fa-4434-91f9-ae1b83c7da40.jpg)

i need it

**Comment by NimaKhajehpour** [comment]
its fine i can make it so that you can select one of the faces and select the desired color at the same time :smile:

**Comment by NimaKhajehpour** [comment]
Hey there, yes i am aware and updates are pending. You should realize that it might take time untill i make the changes and release for fdroid.

**Comment by NimaKhajehpour** [comment]
Why? Didn't you ask to be able to add a face with custom color for any day?

**Comment by NimaKhajehpour** [comment]
To add the face with desired color edit the day. On edit page the first option is to add a face with a color

**Comment by NimaKhajehpour** [comment]
feel free to close the issue if everything is fine

**Comment by NimaKhajehpour** [comment]
ok in the next update i will add a feature to select between custom face or the average of the rates on the day. if you select to have the average then it shows the average ones.
