### ISSUE TITLE
feature request. when you click here to select a custom day for recording

### ISSUE THREAD

**Issue by Wjxfi** [NimaKhajehpour/MyMood#6]
![340470.jpg](https://user-images.githubusercontent.com/113500363/224677265-1040b86c-ff42-4967-b429-0512e898ab86.jpg)

![340440.jpg](https://user-images.githubusercontent.com/113500363/224676935-9d6d7aa4-04fa-4434-91f9-ae1b83c7da40.jpg)

**Comment by NimaKhajehpour** [comment]
can you provide more detail on what exactly do you want to happen. thanks for the request :heart:
